from PySide6.QtWidgets import QMainWindow
from src.layouts.dashboard import DashboardLayout  # The name of the class generated by uic
from src.workers.retrieve import RetrievalWorker
from PySide6.QtCore import QThread


class DashboardScreen(QMainWindow, DashboardLayout):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  # This loads the Designer layout

        # Now you can connect your button just like before!
        self.btn_retrieve.clicked.connect(self.do_something)

    def do_something(self):
        self.btn_retrieve.setEnabled(False)
        self.btn_retrieve.setText("Retrieving...")

        self.thread = QThread()
        self.worker = RetrievalWorker()

        # Move worker to the new thread
        self.worker.moveToThread(self.thread)

        # Connect Signals
        self.thread.started.connect(self.worker.run)
        self.worker.progress.connect(self.progressBar.setValue)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)
        self.thread.finished.connect(self.on_finished)

        # Start the thread
        self.thread.start()

    def on_finished(self):
        self.btn_retrieve.setEnabled(True)
        self.btn_retrieve.setText("Retrieval Done!")

